-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSoqh+usdc5CTftes
Aqo16QFXHAX2hQ+CrdsZzriUdmWgCgYIKoZIzj0DAQehRANCAAQTIgnaRZ3YUHlQ
lQJnIj7EixbZYLlRY+hC5LS/cqc2WMGZATzsw1x6cfTzVRzTYY8Ql/BJ8PPy4YYs
U5yIY4D/
-----END PRIVATE KEY-----